### ISSUE TITLE
Criando novas categorias e tags

### ISSUE THREAD

**Issue by brunopulis** [nandomoreirame/nandomoreira-jekyll-theme#3]
Primeiramente parabéns pelo seu tema estou usando ele e gostando bastante! :) 

Vi que no diretório de categories e tags existem arquivos **.html** criados, minha dúvida é para cada categoria e tag's devo criar esses arquivos? 

Abraços,
Bruno.

**Comment by nandomoreirame** [comment]
Opa @brunopulis tranquilo?
Sim, para cada categoria e tag você precisa criar um arquivo html, apenas para o Jekyll montar o arquivo estático no final, esses arquivos vão usar os layouts `source/_layouts/category.html` e `source/_layouts/tags.html` pra montar os arquivos finais.
Essa foi meio que uma "gambiarra" que encontrei para criar categorias no jekyll, ele não te essa funcionalidade nativamente :grin:

**Comment by brunopulis** [comment]
@nandomoreirame Muito obrigado! :+1:
