### ISSUE TITLE
How can I add a new category?

### ISSUE THREAD

**Issue by Desgard** [nandomoreirame/nandomoreira-jekyll-theme#6]
How can I add a new category?

I add code in `categories.yml` and add a html file in category folder, but my post can't find the category which I added.

**Comment by zhangxulong** [comment]
categories.yml
categories.html
tag.yml
tag.html

**Comment by zhangxulong** [comment]
modify your add html's content

**Comment by nandomoreirame** [comment]
Run rake task for create categories;

Look here: https://github.com/nandomoreirame/nandomoreira-jekyll-theme/blob/master/Rakefile#L131-L159

**Comment by zhangxulong** [comment]
good good is good, I understand it . change the new-tag and new-category as you want add .
and run 
rake tag
rake new-category
will add the html files and modify yml contends as append. 
thanks 
now I knew the rakefile is some functions not just the default: rake public.

**Comment by Desgard** [comment]
Thx for the answers of @zhangxulong and author! 😄
